#!/usr/bin/env bash
#congure Nginx sever to listen on port 80

# creates a symbolic link (-s option) between the nginx confuguration file and
# the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart enginx
service nginx restart
# terminates the first nginx process IO
kill "$(pgrep 'nginx' | head -1)"