#!/usr/bin/env bash
# This script displays content of the current directory in a list format
# Where only the part of the name after first dash is displayed

for _ in *
do
    echo "$_" | cut -f 2 -d '-'
done